version: "3.5"
services:
  web:
    build: .
    volumes:
      - ./index.rst:/app/index.rst
      - ./executive_summary.rst:/app/executive_summary.rst
      - ./images:/app/images
      - ./1_introduction.rst:/app/1_introduction.rst
      - ./2_cloud_computing.rst:/app/2_cloud_computing.rst
      - ./3_the_opportunities_and_challenges_of_cloud_computing.rst:/app/3_the_opportunities_and_challenges_of_cloud_computing.rst
      - ./4_cloud_strategy_for_the_public_administration.rst:/app/4_cloud_strategy_for_the_public_administration.rst
      - ./5_public_administration_s_migration_to_the_loud.rst:/app/5_public_administration_s_migration_to_the_loud.rst
      - ./6_adopting_the_cloud_strategy.rst:/app/6_adopting_the_cloud_strategy.rst
    ports:
      - "8000:8000"
